### ISSUE TITLE
Invoicing page should provide more statistics

### ISSUE THREAD

**Issue by wshands** [DataBiosphere/cgp-dashboard-service#43]
The invoicing page should add more statistics for costs so that this does not need to be done manually. An example of what is needed is here https://docs.google.com/spreadsheets/d/1AuBqQcUE97NmLW0BuAGSZT5eZfb3suu1amdxusmsNik/edit#gid=0

(let wshands know if you cannot access it)

**Comment by achave11** [comment]
Invoicing is being put aside. This ticket is being reprioritized.
