### ISSUE TITLE
create Makefile to build bagit lambda

### ISSUE THREAD

**Issue by mjkrause** [DataBiosphere/cgp-dashboard-service#65]
relates to #https://github.com/DataBiosphere/bagit-firecloud-lambda/issues/2

**Comment by coverbeck** [comment]
This looks like a duplicate of DataBiosphere/bagit-firecloud-lambda#2

**Comment by mikebaumann** [comment]
Closing, as this is a duplicate of DataBiosphere/bagit-firecloud-lambda#2
