### ISSUE TITLE
Handle Large Datasets in Export to FireCloud

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/cgp-dashboard-service#68]
Currently, we take all the selected data and put it into a bagit, and send that bagit to the lamba which sends it to FC.

We could instead create multiple bagits, of smaller sizes.

This would get us around the potential lambda timeout issue.

This ticket is moved from:https://github.com/DataBiosphere/dcc-dashboard-service/issues/11

**Comment by cricketsloan** [comment]
Michael B and I think that this should be deferred

**Comment by coverbeck** [comment]
I think we can defer, and I am going to close this. With #11, FireCloud will handle the import, so this is mainly moot.

I suppose some sort of similar issue could arise when we persist the bagit to the collections service, but if so, we should create a new ticket for it at that time.
